@startuml
participant "Client"
box "PEP" #LightBlue
participant Proxy
participant "Resource API"
end box
participant ADES
participant "Policy API"

participant "Login Service"

== Component Authentication ==
ADES -> "Login Service": Client Credentials Authentication
"Login Service" --> ADES: API Access Token


autonumber

== Deployment Process ==
Client -> Proxy: Deploy Process
Proxy -> ADES: Deploy Process (+JWT)
activate ADES
ADES -> "Resource API": POST /resource {"uri": "/wps3/processes/<process>", "scope": "protected_access"}
"Resource API" --> ADES: return resource_id
ADES -> "Policy API": GET /public/templates/ownership
"Policy API" --> ADES: return ownership_policy
ADES -> ADES: Policy Customization (add owner)
ADES -> "Policy API": POST /policies/{resource_id} [ownership_policy]
"Policy API" --> ADES: OK (201)
deactivate ADES
@enduml
