@startuml "UMA Register Permission"
autonumber
autoactivate on
participant Client
participant "Resource Server" as RS
box "Authorization Server"
participant "Authorization API" as AuthzAPI
participant "Protection API" as ProtAPI
end box
Client -> RS : GET resource (?RPT)
opt request has RPT
  RS -> ProtAPI : Check RPT status (PAT,RPT)
  return RPT status = NotOK
end
RS -> ProtAPI : Register Requested Permission (PAT)
return Permission Ticket
return Permission Ticket + AS Location
note over Client, ProtAPI
  Sequence continues with flow 'UMA Client Request Authorization'
end note
@enduml